"""Render the podman-pod test script for a target service and its dependencies."""

import dataclasses
import shlex
from pathlib import Path
from typing import Any

from compose2pod.graph import depends_on, hostnames, startup_order
from compose2pod.healthcheck import health_cmd, interval_seconds
from compose2pod.keys import SERVICE_KEYS, Token, _Expand, _key_value_pairs
from compose2pod.secrets import referenced_secret_names, secret_create_lines, secret_flags, secret_referenced_variables
from compose2pod.shell import to_shell, variable_names


HEALTHY_WAIT_BUDGET_SECONDS = 120


def image_for(svc: dict[str, Any], ci_image: str) -> Token:
    """Services with a build section run the freshly built CI image."""
    if "build" in svc:
        return ci_image
    return _Expand(value=svc["image"])


def command_tokens(svc: dict[str, Any]) -> list[Token]:
    """Service command as argv tokens; compose string form means shell form."""
    command = svc.get("command")
    if command is None:
        return []
    if isinstance(command, str):
        return ["/bin/sh", "-c", _Expand(value=command)]
    return [_Expand(value=str(token)) for token in command]


def entrypoint_tokens(svc: dict[str, Any]) -> list[Token]:
    """Service entrypoint as argv tokens; compose string form means shell form."""
    entrypoint = svc.get("entrypoint")
    if entrypoint is None:
        return []
    if isinstance(entrypoint, str):
        return ["/bin/sh", "-c", _Expand(value=entrypoint)]
    return [_Expand(value=str(token)) for token in entrypoint]


def _add_health_flags(flags: list[Token], healthcheck: dict[str, Any]) -> None:
    """Add healthcheck flags to the flags list."""
    cmd = health_cmd(healthcheck.get("test"))
    if cmd is not None:
        flags += ["--health-cmd", _Expand(value=cmd)]
        if "timeout" in healthcheck:
            flags += ["--health-timeout", str(healthcheck["timeout"])]
        if "start_period" in healthcheck:
            flags += ["--health-start-period", str(healthcheck["start_period"])]
        if "retries" in healthcheck:
            flags += ["--health-retries", str(healthcheck["retries"])]


def _add_env_flags(flags: list[Token], svc: dict[str, Any], project_dir: str) -> None:
    """Add -e and --env-file flags to the flags list."""
    # A null environment value means "pass KEY through from the host" (bare `-e KEY`).
    for pair in _key_value_pairs(svc.get("environment") or {}):
        flags += ["-e", _Expand(value=str(pair))]
    env_files = svc.get("env_file") or []
    if isinstance(env_files, str):
        env_files = [env_files]
    for env_file in env_files:
        flags += ["--env-file", _Expand(value=str(Path(project_dir, env_file)))]


def _add_volume_flags(flags: list[Token], svc: dict[str, Any], project_dir: str) -> None:
    """Add -v and --tmpfs flags to the flags list."""
    for volume in svc.get("volumes") or []:
        if ":" not in volume:
            # Anonymous volume: a bare container path, no host source to translate.
            flags += ["-v", _Expand(value=volume)]
            continue
        source, destination = volume.split(":", 1)
        if source.startswith("."):
            # Relative bind mount: resolve against project_dir.
            source = str(Path(project_dir, source))
        # Absolute bind mount (starts with "/") and named volume (bare
        # identifier) are both kept as-is — neither is a path to translate.
        flags += ["-v", _Expand(value=f"{source}:{destination}")]
    tmpfs = svc.get("tmpfs") or []
    if isinstance(tmpfs, str):
        tmpfs = [tmpfs]
    for mount in tmpfs:
        flags += ["--tmpfs", _Expand(value=mount)]


def run_flags(name: str, svc: dict[str, Any], pod: str, hosts: list[str], project_dir: str) -> list[Token]:
    """Flag tokens (unquoted) for `podman run` of one service."""
    flags: list[Token] = ["--pod", pod, "--name", f"{pod}-{name}"]
    for host in hosts:
        flags += ["--add-host", f"{host}:127.0.0.1"]
    _add_env_flags(flags, svc, project_dir)
    _add_volume_flags(flags, svc, project_dir)
    _add_health_flags(flags, svc.get("healthcheck") or {})
    for key, spec in SERVICE_KEYS.items():
        if key in svc:
            flags += spec.emit(svc[key])
    flags += secret_flags(svc, pod)
    return flags


_SCRIPT_HEADER = """\
#!/bin/sh
# Generated by compose2pod -- do not edit, regenerate instead.
set -eu

wait_healthy() {
  ctr=$1
  attempts=$2
  interval=$3
  i=0
  while [ "$i" -lt "$attempts" ]; do
    if podman healthcheck run "$ctr"; then
      return 0
    fi
    i=$((i + 1))
    sleep "$interval"
  done
  echo "wait_healthy: $ctr did not become healthy after $attempts attempts" >&2
  podman logs "$ctr" >&2 || true
  return 1
}
"""


@dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class EmitOptions:
    """Options for emit_script rendering."""

    target: str
    ci_image: str
    command: str
    pod: str
    project_dir: str
    artifacts: list[str]
    allow_exit_codes: list[int]


def _render(tokens: list[Token]) -> str:
    return " ".join(to_shell(token.value) if isinstance(token, _Expand) else shlex.quote(token) for token in tokens)


def _run_tokens(name: str, services: dict[str, Any], options: EmitOptions, hosts: list[str]) -> list[Token]:
    svc = services[name]
    tokens = run_flags(name, svc, options.pod, hosts, options.project_dir)
    entrypoint = entrypoint_tokens(svc)
    if entrypoint:
        tokens += ["--entrypoint", entrypoint[0]]
    tokens.append(image_for(svc, options.ci_image))
    tokens += entrypoint[1:]
    if name == options.target and options.command:
        tokens.extend(shlex.split(options.command))
    elif not isinstance(svc.get("entrypoint"), str):
        # A string (shell-form) entrypoint runs via `sh -c`; the service command
        # is ignored, matching Docker. List/exec form appends the command.
        tokens.extend(command_tokens(svc))
    return tokens


def _emit_target(lines: list[str], run_tokens: list[Token], options: EmitOptions) -> None:
    target_ctr = shlex.quote(f"{options.pod}-{options.target}")
    lines.append("rc=0")
    lines.append(f"podman run {_render(run_tokens)} || rc=$?")
    for artifact in options.artifacts:
        source, destination = artifact.split(":", 1)
        lines.append(f"podman cp {target_ctr}:{shlex.quote(source)} {shlex.quote(destination)} || true")
    allowed = "|".join(str(code) for code in [0, *options.allow_exit_codes])
    lines.append('case "$rc" in')
    lines.append(f"  {allowed}) ;;")
    lines.append('  *) echo "target service failed with exit code $rc" >&2')
    lines.append(
        "     podman inspect --format "
        "'OOMKilled={{.State.OOMKilled}} ExitCode={{.State.ExitCode}}' " + target_ctr + " >&2 || true"
    )
    lines.append("     podman ps -a --format '{{.Names}} {{.Status}}' >&2 || true")
    lines.append('     exit "$rc" ;;')
    lines.append("esac")


def emit_script(compose: dict[str, Any], options: EmitOptions) -> str:
    """Render the full pod test script for `target` and its dependency closure."""
    services = compose["services"]
    hosts = hostnames(services)
    order = startup_order(services, options.target)
    secret_names = referenced_secret_names(services, order)
    completion_gated = {
        dep
        for svc in services.values()
        for dep, condition in depends_on(svc).items()
        if condition == "service_completed_successfully"
    }

    lines = [_SCRIPT_HEADER]
    teardown = f"podman pod rm -f {shlex.quote(options.pod)} >/dev/null 2>&1 || true"
    if secret_names:
        stores = " ".join(f"{options.pod}-{name}" for name in secret_names)
        teardown += f"; podman secret rm {stores} >/dev/null 2>&1 || true"
    lines.append(f"trap '{teardown}' EXIT")
    lines.append(f"podman pod create --name {shlex.quote(options.pod)}")
    lines.extend(secret_create_lines(compose, options.pod, options.project_dir, secret_names))
    waited: set[str] = set()
    for name in order:
        for dep, condition in depends_on(services[name]).items():
            if condition == "service_healthy" and dep not in waited:
                interval = interval_seconds((services[dep].get("healthcheck") or {}).get("interval"))
                attempts = max(HEALTHY_WAIT_BUDGET_SECONDS // interval, 1)
                lines.append(f"wait_healthy {shlex.quote(f'{options.pod}-{dep}')} {attempts} {interval}")
                waited.add(dep)
        run_tokens = _run_tokens(name, services, options, hosts)
        if name == options.target:
            _emit_target(lines, run_tokens, options)
        elif name in completion_gated:
            lines.append(f"podman run --rm {_render(run_tokens)}")
        else:
            lines.append(f"podman run -d {_render(run_tokens)}")
    return "\n".join(lines) + "\n"


def referenced_variables(compose: dict[str, Any], options: EmitOptions) -> list[str]:
    """Variable names the emitted script expands at run time (sorted, unique).

    Reuses the same token construction as `emit_script`, so it counts exactly
    the values that pass through `to_shell` -- never a `${VAR}` in a field that
    is emitted literally, and never the `--command` override (a literal CLI value).
    """
    services = compose["services"]
    hosts = hostnames(services)
    order = startup_order(services, options.target)
    names: set[str] = set()
    for name in order:
        for token in _run_tokens(name, services, options, hosts):
            if isinstance(token, _Expand):
                names.update(variable_names(token.value))
    names |= secret_referenced_variables(compose, options.project_dir, referenced_secret_names(services, order))
    return sorted(names)
