"""Render the podman-pod test script for a target service and its dependencies."""

import dataclasses
import re
import shlex
from pathlib import Path
from typing import Any

from compose2pod import stores
from compose2pod.exceptions import UnsupportedComposeError
from compose2pod.graph import depends_on, hostnames, startup_order
from compose2pod.healthcheck import health_cmd, interval_seconds
from compose2pod.keys import SERVICE_KEYS, Expand, Token, key_value_pairs
from compose2pod.pod import pod_create_flags
from compose2pod.resources import deploy_resource_flags
from compose2pod.shell import to_shell, variable_names


HEALTHY_WAIT_BUDGET_SECONDS = 120
POD_NAME_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")


def image_for(svc: dict[str, Any], ci_image: str) -> Token:
    """Services with a build section run the freshly built CI image."""
    if "build" in svc:
        return ci_image
    return Expand(value=svc["image"])


def command_tokens(svc: dict[str, Any]) -> list[Token]:
    """Service command as argv tokens; compose string form means shell form."""
    command = svc.get("command")
    if command is None:
        return []
    if isinstance(command, str):
        return ["/bin/sh", "-c", Expand(value=command)]
    return [Expand(value=str(token)) for token in command]


def entrypoint_tokens(svc: dict[str, Any]) -> list[Token]:
    """Service entrypoint as argv tokens; compose string form means shell form."""
    entrypoint = svc.get("entrypoint")
    if entrypoint is None:
        return []
    if isinstance(entrypoint, str):
        return ["/bin/sh", "-c", Expand(value=entrypoint)]
    return [Expand(value=str(token)) for token in entrypoint]


def _health_flags(healthcheck: dict[str, Any]) -> list[Token]:
    """Healthcheck flag tokens."""
    flags: list[Token] = []
    cmd = health_cmd(healthcheck.get("test"))
    if cmd is not None:
        flags += ["--health-cmd", Expand(value=cmd)]
        if "timeout" in healthcheck:
            flags += ["--health-timeout", str(healthcheck["timeout"])]
        if "start_period" in healthcheck:
            flags += ["--health-start-period", str(healthcheck["start_period"])]
        if "retries" in healthcheck:
            flags += ["--health-retries", str(healthcheck["retries"])]
    return flags


def _env_flags(svc: dict[str, Any], project_dir: str) -> list[Token]:
    """-e and --env-file flag tokens."""
    flags: list[Token] = []
    # A null environment value means "pass KEY through from the host" (bare `-e KEY`).
    for pair in key_value_pairs(svc.get("environment") or {}):
        flags += ["-e", Expand(value=str(pair))]
    env_files = svc.get("env_file") or []
    if isinstance(env_files, str):
        env_files = [env_files]
    for env_file in env_files:
        flags += ["--env-file", Expand(value=str(Path(project_dir, env_file)))]
    return flags


def _volume_flags(svc: dict[str, Any], project_dir: str) -> list[Token]:
    """-v and --tmpfs flag tokens."""
    flags: list[Token] = []
    for volume in svc.get("volumes") or []:
        if ":" not in volume:
            # Anonymous volume: a bare container path, no host source to translate.
            flags += ["-v", Expand(value=volume)]
            continue
        source, destination = volume.split(":", 1)
        if source.startswith("."):
            # Relative bind mount: resolve against project_dir.
            source = str(Path(project_dir, source))
        # Absolute bind mount (starts with "/") and named volume (bare
        # identifier) are both kept as-is — neither is a path to translate.
        flags += ["-v", Expand(value=f"{source}:{destination}")]
    tmpfs = svc.get("tmpfs") or []
    if isinstance(tmpfs, str):
        tmpfs = [tmpfs]
    for mount in tmpfs:
        flags += ["--tmpfs", Expand(value=mount)]
    return flags


def run_flags(name: str, svc: dict[str, Any], pod: str, project_dir: str) -> list[Token]:
    """Flag tokens (unquoted) for `podman run` of one service."""
    flags: list[Token] = ["--pod", pod, "--name", f"{pod}-{name}"]
    flags += _env_flags(svc, project_dir)
    flags += _volume_flags(svc, project_dir)
    flags += _health_flags(svc.get("healthcheck") or {})
    for key, spec in SERVICE_KEYS.items():
        if key in svc:
            flags += spec.emit(svc[key])
    flags += stores.flags(svc, pod)
    flags += deploy_resource_flags(svc)
    return flags


_SCRIPT_HEADER = """\
#!/bin/sh
# Generated by compose2pod -- do not edit, regenerate instead.
set -eu

podman_version=$(podman version --format '{{.Client.Version}}' 2>/dev/null) || podman_version="unknown"
podman_major=$(echo "$podman_version" | cut -d. -f1)
case "$podman_major" in
  ''|*[!0-9]*) ;;  # unparseable -- skip rather than false-positive
  *) if [ "$podman_major" -lt 6 ]; then
       echo "warning: podman $podman_version detected; compose2pod requires podman >= 6.0.0" >&2
       echo "warning: podman < 6.0.0 has a bug where a container stopping in a multi-container" >&2
       echo "pod wipes /etc/hosts for the whole pod (fixed in 6.0.0) -- name resolution between" >&2
       echo "services may fail unpredictably" >&2
     fi ;;
esac

wait_healthy() {
  ctr=$1
  attempts=$2
  interval=$3
  i=0
  while [ "$i" -lt "$attempts" ]; do
    if podman healthcheck run "$ctr"; then
      return 0
    fi
    i=$((i + 1))
    sleep "$interval"
  done
  echo "wait_healthy: $ctr did not become healthy after $attempts attempts" >&2
  podman logs "$ctr" >&2 || true
  return 1
}
"""


@dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class EmitOptions:
    """Options for emit_script rendering."""

    target: str
    ci_image: str
    command: str
    pod: str
    project_dir: str
    artifacts: list[str]
    allow_exit_codes: list[int]


@dataclasses.dataclass(frozen=True, slots=True, kw_only=True)
class PlannedScript:
    """The rendered pod script and the run-time variables it expands.

    Both are products of a single `_plan` traversal, so they cannot drift.
    """

    script: str
    variables: list[str]


def _render(tokens: list[Token]) -> str:
    return " ".join(to_shell(token.value) if isinstance(token, Expand) else shlex.quote(token) for token in tokens)


def _collect_vars(tokens: list[Token], names: set[str]) -> None:
    """Add the run-time variables any `Expand` tokens expand to `names`."""
    for token in tokens:
        if isinstance(token, Expand):
            names.update(variable_names(token.value))


def run_tokens(name: str, services: dict[str, Any], options: EmitOptions) -> list[Token]:
    svc = services[name]
    tokens = run_flags(name, svc, options.pod, options.project_dir)
    entrypoint = entrypoint_tokens(svc)
    if entrypoint:
        tokens += ["--entrypoint", entrypoint[0]]
    tokens.append(image_for(svc, options.ci_image))
    tokens += entrypoint[1:]
    if name == options.target and options.command:
        tokens.extend(shlex.split(options.command))
    elif not isinstance(svc.get("entrypoint"), str):
        # A string (shell-form) entrypoint runs via `sh -c`; the service command
        # is ignored, matching Docker. List/exec form appends the command.
        tokens.extend(command_tokens(svc))
    return tokens


def _emit_target(lines: list[str], tokens: list[Token], options: EmitOptions) -> None:
    target_ctr = shlex.quote(f"{options.pod}-{options.target}")
    lines.append("rc=0")
    lines.append(f"podman run {_render(tokens)} || rc=$?")
    for artifact in options.artifacts:
        source, destination = artifact.split(":", 1)
        lines.append(f"podman cp {target_ctr}:{shlex.quote(source)} {shlex.quote(destination)} || true")
    allowed = "|".join(str(code) for code in [0, *options.allow_exit_codes])
    lines.append('case "$rc" in')
    lines.append(f"  {allowed}) ;;")
    lines.append('  *) echo "target service failed with exit code $rc" >&2')
    lines.append(
        "     podman inspect --format "
        "'OOMKilled={{.State.OOMKilled}} ExitCode={{.State.ExitCode}}' " + target_ctr + " >&2 || true"
    )
    lines.append("     podman ps -a --format '{{.Names}} {{.Status}}' >&2 || true")
    lines.append('     exit "$rc" ;;')
    lines.append("esac")


def _validate_options(options: EmitOptions) -> None:
    """Check option values emit destructures (artifacts are split on ':')."""
    for artifact in options.artifacts:
        if ":" not in artifact:
            msg = f"artifact {artifact!r} must be in SRC:DST form"
            raise UnsupportedComposeError(msg)


def _plan(compose: dict[str, Any], options: EmitOptions) -> PlannedScript:
    """Walk the target's dependency closure once, building the script and its variables.

    Every token source is visited a single time and feeds both outputs: each
    service's `run_tokens` and the `pod_create_flags` render into lines *and*
    have their `Expand` variables collected, so the script and the variable
    list cannot disagree about what the script expands at run time.
    """
    _validate_options(options)
    services = compose["services"]
    hosts = hostnames(services)
    order = startup_order(services, options.target)
    completion_gated = {
        dep
        for svc in services.values()
        for dep, condition in depends_on(svc).items()
        if condition == "service_completed_successfully"
    }
    names: set[str] = set()

    lines = [_SCRIPT_HEADER]
    teardown = f"podman pod rm -f {shlex.quote(options.pod)} >/dev/null 2>&1 || true"
    store_teardown = stores.teardown_line(compose, order, options.pod)
    if store_teardown:
        teardown += f"; {store_teardown}"
    lines.append(f"trap '{teardown}' EXIT")
    pod_flags = pod_create_flags(services, order, hosts)
    _collect_vars(pod_flags, names)
    pod_create = f"podman pod create --name {shlex.quote(options.pod)}"
    if pod_flags:
        pod_create += " " + _render(pod_flags)
    lines.append(pod_create)
    lines.extend(stores.create_lines(compose, order, options.pod, options.project_dir))
    names |= stores.referenced_variables(compose, order, options.project_dir)
    waited: set[str] = set()
    for name in order:
        for dep, condition in depends_on(services[name]).items():
            if condition == "service_healthy" and dep not in waited:
                interval = interval_seconds((services[dep].get("healthcheck") or {}).get("interval"))
                attempts = max(HEALTHY_WAIT_BUDGET_SECONDS // interval, 1)
                lines.append(f"wait_healthy {shlex.quote(f'{options.pod}-{dep}')} {attempts} {interval}")
                waited.add(dep)
        tokens = run_tokens(name, services, options)
        _collect_vars(tokens, names)
        if name == options.target:
            _emit_target(lines, tokens, options)
        elif name in completion_gated:
            lines.append(f"podman run --rm {_render(tokens)}")
        else:
            lines.append(f"podman run -d {_render(tokens)}")
    return PlannedScript(script="\n".join(lines) + "\n", variables=sorted(names))


def emit_script(compose: dict[str, Any], options: EmitOptions) -> str:
    """Render the full pod test script for `target` and its dependency closure."""
    if not POD_NAME_PATTERN.fullmatch(options.pod):
        msg = f"invalid pod name {options.pod!r}"
        raise UnsupportedComposeError(msg)
    return _plan(compose, options).script


def referenced_variables(compose: dict[str, Any], options: EmitOptions) -> list[str]:
    """Variable names the emitted script expands at run time (sorted, unique).

    Projects the same `_plan` traversal `emit_script` renders from, so it counts
    exactly the values that pass through `to_shell` -- never a `${VAR}` in a
    field emitted literally, and never the `--command` override (a literal CLI
    value).
    """
    return _plan(compose, options).variables
