"""Render the podman-pod test script for a target service and its dependencies."""

import dataclasses
import shlex
from pathlib import Path
from typing import Any

from compose2pod.graph import depends_on, hostnames, startup_order
from compose2pod.healthcheck import health_cmd, interval_seconds


HEALTHY_WAIT_BUDGET_SECONDS = 120


def image_for(svc: dict[str, Any], ci_image: str) -> str:
    """Services with a build section run the freshly built CI image."""
    if "build" in svc:
        return ci_image
    return svc["image"]


def command_tokens(svc: dict[str, Any]) -> list[str]:
    """Service command as argv tokens; compose string form means shell form."""
    command = svc.get("command")
    if command is None:
        return []
    if isinstance(command, str):
        return ["/bin/sh", "-c", command]
    return list(command)


def _add_health_flags(flags: list[str], healthcheck: dict[str, Any]) -> None:
    """Add healthcheck flags to the flags list."""
    cmd = health_cmd(healthcheck.get("test"))
    if cmd is not None:
        flags += ["--health-cmd", cmd]
        if "timeout" in healthcheck:
            flags += ["--health-timeout", str(healthcheck["timeout"])]
        if "start_period" in healthcheck:
            flags += ["--health-start-period", str(healthcheck["start_period"])]
        if "retries" in healthcheck:
            flags += ["--health-retries", str(healthcheck["retries"])]


def run_flags(name: str, svc: dict[str, Any], pod: str, hosts: list[str], project_dir: str) -> list[str]:
    """Flag tokens (unquoted) for `podman run` of one service."""
    flags = ["--pod", pod, "--name", f"{pod}-{name}"]
    for host in hosts:
        flags += ["--add-host", f"{host}:127.0.0.1"]
    environment = svc.get("environment") or {}
    pairs = environment if isinstance(environment, list) else [f"{k}={v}" for k, v in environment.items()]
    for pair in pairs:
        flags += ["-e", pair]
    env_files = svc.get("env_file") or []
    if isinstance(env_files, str):
        env_files = [env_files]
    for env_file in env_files:
        flags += ["--env-file", str(Path(project_dir, env_file))]
    for volume in svc.get("volumes") or []:
        source, destination = volume.split(":", 1)
        if not source.startswith("/"):
            source = str(Path(project_dir, source))
        flags += ["-v", f"{source}:{destination}"]
    healthcheck = svc.get("healthcheck") or {}
    _add_health_flags(flags, healthcheck)
    return flags


_SCRIPT_HEADER = """\
#!/bin/sh
# Generated by compose2pod -- do not edit, regenerate instead.
set -eu

wait_healthy() {
  ctr=$1
  attempts=$2
  interval=$3
  i=0
  while [ "$i" -lt "$attempts" ]; do
    if podman healthcheck run "$ctr"; then
      return 0
    fi
    i=$((i + 1))
    sleep "$interval"
  done
  echo "wait_healthy: $ctr did not become healthy after $attempts attempts" >&2
  podman logs "$ctr" >&2 || true
  return 1
}
"""


@dataclasses.dataclass(frozen=True)
class EmitOptions:
    """Options for emit_script rendering."""

    target: str
    ci_image: str
    command: str
    pod: str
    project_dir: str
    artifacts: list[str]
    allow_exit_codes: list[int]


def _render(tokens: list[str]) -> str:
    return " ".join(shlex.quote(token) for token in tokens)


def _run_tokens(name: str, services: dict[str, Any], options: EmitOptions, hosts: list[str]) -> list[str]:
    svc = services[name]
    tokens = run_flags(name, svc, options.pod, hosts, options.project_dir)
    tokens.append(image_for(svc, options.ci_image))
    if name == options.target and options.command:
        tokens.extend(shlex.split(options.command))
    else:
        tokens.extend(command_tokens(svc))
    return tokens


def _emit_target(lines: list[str], run_tokens: list[str], options: EmitOptions) -> None:
    target_ctr = shlex.quote(f"{options.pod}-{options.target}")
    lines.append("rc=0")
    lines.append(f"podman run {_render(run_tokens)} || rc=$?")
    for artifact in options.artifacts:
        source, destination = artifact.split(":", 1)
        lines.append(f"podman cp {target_ctr}:{shlex.quote(source)} {shlex.quote(destination)} || true")
    allowed = "|".join(str(code) for code in [0, *options.allow_exit_codes])
    lines.append('case "$rc" in')
    lines.append(f"  {allowed}) ;;")
    lines.append('  *) echo "target service failed with exit code $rc" >&2')
    lines.append(
        "     podman inspect --format "
        "'OOMKilled={{.State.OOMKilled}} ExitCode={{.State.ExitCode}}' " + target_ctr + " >&2 || true"
    )
    lines.append("     podman ps -a --format '{{.Names}} {{.Status}}' >&2 || true")
    lines.append('     exit "$rc" ;;')
    lines.append("esac")


def emit_script(compose: dict[str, Any], options: EmitOptions) -> str:
    """Render the full pod test script for `target` and its dependency closure."""
    services = compose["services"]
    hosts = hostnames(services)
    order = startup_order(services, options.target)
    completion_gated = {
        dep
        for svc in services.values()
        for dep, condition in depends_on(svc).items()
        if condition == "service_completed_successfully"
    }

    lines = [_SCRIPT_HEADER]
    lines.append(f"trap 'podman pod rm -f {shlex.quote(options.pod)} >/dev/null 2>&1 || true' EXIT")
    lines.append(f"podman pod create --name {shlex.quote(options.pod)}")
    waited: set[str] = set()
    for name in order:
        for dep, condition in depends_on(services[name]).items():
            if condition == "service_healthy" and dep not in waited:
                interval = interval_seconds((services[dep].get("healthcheck") or {}).get("interval"))
                attempts = max(HEALTHY_WAIT_BUDGET_SECONDS // interval, 1)
                lines.append(f"wait_healthy {shlex.quote(f'{options.pod}-{dep}')} {attempts} {interval}")
                waited.add(dep)
        run_tokens = _run_tokens(name, services, options, hosts)
        if name == options.target:
            _emit_target(lines, run_tokens, options)
        elif name in completion_gated:
            lines.append(f"podman run --rm {_render(run_tokens)}")
        else:
            lines.append(f"podman run -d {_render(run_tokens)}")
    return "\n".join(lines) + "\n"
